import React from 'react';
import {
  Sparkles,
  Code,
  Cpu,
  Palette,
  Cloud,
  Wrench,
  Folder,
  Bookmark,
  Globe,
  Search,
  Compass,
  Github,
  Shield,
  Star,
  ExternalLink,
  BookOpen,
  Film,
  Music,
  ShoppingBag,
  Zap,
  Terminal,
  Database,
  Layers,
  Heart,
  Briefcase,
  LucideIcon,
} from 'lucide-react';

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: 'Sparkles', icon: Sparkles },
  { name: 'Code', icon: Code },
  { name: 'Cpu', icon: Cpu },
  { name: 'Palette', icon: Palette },
  { name: 'Cloud', icon: Cloud },
  { name: 'Wrench', icon: Wrench },
  { name: 'Folder', icon: Folder },
  { name: 'Bookmark', icon: Bookmark },
  { name: 'Globe', icon: Globe },
  { name: 'Compass', icon: Compass },
  { name: 'Github', icon: Github },
  { name: 'Shield', icon: Shield },
  { name: 'Star', icon: Star },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Film', icon: Film },
  { name: 'Music', icon: Music },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'Zap', icon: Zap },
  { name: 'Terminal', icon: Terminal },
  { name: 'Database', icon: Database },
  { name: 'Layers', icon: Layers },
  { name: 'Heart', icon: Heart },
  { name: 'Briefcase', icon: Briefcase },
];

const iconMap: Record<string, LucideIcon> = {
  Sparkles,
  Code,
  Cpu,
  Palette,
  Cloud,
  Wrench,
  Folder,
  Bookmark,
  Globe,
  Search,
  Compass,
  Github,
  Shield,
  Star,
  ExternalLink,
  BookOpen,
  Film,
  Music,
  ShoppingBag,
  Zap,
  Terminal,
  Database,
  Layers,
  Heart,
  Briefcase,
};

export function renderCategoryIcon(iconName: string | undefined, className = 'w-4 h-4'): React.ReactElement {
  const IconComponent = (iconName && iconMap[iconName]) ? iconMap[iconName] : Folder;
  return <IconComponent className={className} />;
}
